# Generated by Django 6.0.1 on 2026-01-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParticipationAttachment",
        ),
    ]
