# Generated by Django 6.0.1 on 2026-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0002_delete_participationattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantinfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="participants/"),
        ),
    ]
