# Generated by Django 6.0.1 on 2026-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0003_participantinfo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantinfo",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantinfo",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
    ]
