# Generated by Django 6.0.1 on 2026-01-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_event_starting_date"),
        ("participant", "0003_participantinfo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_teams",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "name")},
            },
        ),
        migrations.CreateModel(
            name="StaffTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("H", "Head"), ("S", "SubHead"), ("M", "Member")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_teams",
                        to="participant.participant",
                    ),
                ),
                (
                    "staff_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="staff.staffteam",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "staff_team")},
            },
        ),
    ]
